# Generated by Django 5.0.7 on 2024-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsAbscent', models.BooleanField(default=False)),
                ('IsLate', models.BooleanField(default=False)),
                ('LateDuration', models.IntegerField(blank=True, choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes')], null=True)),
                ('Date', models.DateField()),
                ('AbsenceStartTime', models.TimeField(blank=True, null=True)),
                ('AbsenceEndTime', models.TimeField(blank=True, null=True)),
                ('Student', models.ManyToManyField(related_name='presences', to='user.user')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
