# Generated by Django 5.0.7 on 2024-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='AbsenceEndTime',
            new_name='absence_end_time',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='AbsenceStartTime',
            new_name='absence_start_time',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='IsAbscent',
            new_name='is_abscent',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='IsLate',
            new_name='is_late',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='LateDuration',
            new_name='late_duration',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='Student',
            new_name='student',
        ),
    ]
