# Generated by Django 5.0.7 on 2024-08-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Age', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(max_length=255)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('Doc', models.ManyToManyField(blank=True, related_name='user_documents', to='doc.document')),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_user', to='user.userlevel')),
                ('Specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spe_user', to='user.userspecialization')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
