# Generated by Django 5.0.7 on 2024-08-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Class',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Doc',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='userlevel',
            old_name='Class',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='userspecialization',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='is_intervenant',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est un intervenant"),
        ),
    ]
