# Generated by Django 5.0.7 on 2024-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_address_user_address_rename_age_user_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_intervenant',
        ),
    ]
