# Generated by Django 5.0.7 on 2024-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='FilePath',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Name',
            new_name='name',
        ),
    ]
