# Generated by Django 5.0.7 on 2024-07-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Password', models.CharField(max_length=255)),
                ('Photo', models.BinaryField(blank=True, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('Role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=20)),
            ],
            options={
                'db_table': 'user_table',
                'ordering': ('-UserId',),
                'managed': False,
            },
        ),
    ]
