# Generated by Django 5.0.7 on 2024-08-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note')),
                ('Coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coefficient')),
                ('Subject', models.CharField(max_length=255, verbose_name='Matière')),
                ('Label', models.TextField(blank=True, null=True, verbose_name='Étiquette')),
                ('TotalScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score total')),
                ('ClassLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_note', to='user.userlevel', verbose_name='Niveau de classe')),
                ('Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spe_note', to='user.userspecialization', verbose_name='Spécialisation')),
                ('Students', models.ManyToManyField(blank=True, related_name='enrolled_note', to='user.user', verbose_name='Étudiants')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_note', to='user.user', verbose_name='Enseignant')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
