# Generated by Django 5.0.7 on 2024-08-08 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Students',
        ),
        migrations.AddField(
            model_name='note',
            name='Students',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_note', to='user.user', verbose_name='Étudiants'),
            preserve_default=False,
        ),
    ]
