# Generated by Django 5.0.7 on 2024-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_note_students_note_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='ClassLevel',
            new_name='class_level',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Coefficient',
            new_name='coefficient',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Students',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='TotalScore',
            new_name='total_score',
        ),
    ]
