# Generated by Django 5.0.7 on 2024-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_rename_classlevel_note_class_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='total_score',
        ),
    ]
