# Generated by Django 5.0.7 on 2024-08-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_total_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='students',
            new_name='student',
        ),
    ]
