# Generated by Django 5.0.7 on 2024-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_rename_students_note_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Noté sur'),
        ),
    ]
