# Generated by Django 5.0.7 on 2024-08-05 14:00

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Subject', models.CharField(max_length=255)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Place', models.CharField(max_length=255)),
                ('Color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('ClassLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='user.userlevel')),
                ('Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spe_courses', to='user.userspecialization')),
                ('Students', models.ManyToManyField(blank=True, related_name='enrolled_courses', to='user.user')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to='user.user')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
