# Generated by Django 5.0.7 on 2024-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ClassLevel',
            new_name='class_level',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='StartTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Students',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
